# Generated by Django 5.0.2 on 2026-03-09 19:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='organic_certified',
            new_name='is_organic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='harvest_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.AddField(
            model_name='product',
            name='allergen_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.producer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=1, help_text='e.g., per kg, per bunch', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEG', 'Vegetables'), ('FRUIT', 'Fruit'), ('MEAT', 'Meat & Poultry'), ('DAIRY', 'Dairy'), ('BAKERY', 'Bakery')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
