# Generated by Django 5.0.2 on 2026-03-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_basketitem_id_alter_customerorder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergen_information',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
