# Generated by Django 5.0.2 on 2026-03-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_product_allergen_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('READY', 'Ready for Delivery'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
    ]
