# Generated by Django 5.0.2 on 2026-03-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seasonal_from',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('WINTER', 'Winter')], default='SPRING', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='seasonal_to',
            field=models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('WINTER', 'Winter')], default='WINTER', max_length=10),
        ),
    ]
