# Generated by Django 5.0.2 on 2026-04-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_recipe'),
        ('marketplace', '0015_product_discount_percent_product_is_surplus'),
    ]

    operations = [
    ]
