# Generated by Django 5.0.2 on 2026-04-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_merge_20260327_1317'),
        ('marketplace', '0016_merge_20260407_1033'),
    ]

    operations = [
    ]
