# Generated by Django 5.0.2 on 2026-04-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_merge_20260327_1309'),
        ('marketplace', '0019_recipeimage'),
    ]

    operations = [
    ]
