# Generated by Django 5.0.2 on 2026-04-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_merge_20260424_1420'),
        ('marketplace', '0020_merge_20260424_0001'),
    ]

    operations = [
    ]
