# Generated by Django 5.0.2 on 2026-04-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_merge_20260427_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
