# Generated by Django 5.0.2 on 2026-04-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_recurring_order_schedule_and_next_order_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorder',
            name='delivery_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2),
        ),
        migrations.AddField(
            model_name='recurringorder',
            name='recurrence_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
