# Generated by Django 5.0.2 on 2026-05-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_merge_20260429_1820'),
        ('marketplace', '0022_productreview_is_anonymous'),
        ('marketplace', '0023_customerorder_recurring_source_fields'),
    ]

    operations = [
    ]
